### DISCUSSION TITLE
v0.8.5

### DISCUSSION THREAD

**Discussion by idursun** [idursun/jjui#61] [Announcements]
### Auto refresh
JJUI can now auto refresh if specified in the configuration (#58)

```toml
[ui]
#in seconds
auto_refresh_interval = 10
```

### Bookmarks
Bookmark window now sorts the possible move operations based on the distance to the bookmarks from the selected revision. Movable bookmarks that are close to the selection are listed at top, and the ones that should be run with `--allow-backwards` are listed at the bottom. (#57)

### Preview
Added ability to expand and shrink preview window. (#56)
 
Expand and shrink are mapped to `ctrl+h` and `ctrl+l` by default. Default initial percentage is 50% (same as before), and increments are configured to be 5%.

```toml
[keys.preview]
  expand = ["ctrl+h"]
  shrink = ["ctrl+l"]
[preview]
  width_percentage = 50.0
  width_increment_percentage = 5.0
```

Additionally, preview window now passes the `extra_args` configuration value to  `jj show` and `jj diff` commands when invoking them.

## Contributions
* Adding nix flake. by @vic in https://github.com/idursun/jjui/pull/50
* docs: fix code block formatting in readme by @bnjmnt4n in https://github.com/idursun/jjui/pull/53
* chore(nix): Add flake check GH action. by @vic in https://github.com/idursun/jjui/pull/60

## New Contributors
* @vic made their first contribution in https://github.com/idursun/jjui/pull/50
* @bnjmnt4n made their first contribution in https://github.com/idursun/jjui/pull/53

**Full Changelog**: https://github.com/idursun/jjui/compare/v0.8.4...v0.8.5

<hr /><em>This discussion was created from the release <a href='https://github.com/idursun/jjui/releases/tag/v0.8.5'>v0.8.5</a>.</em>
