### DISCUSSION TITLE
Feedback request for custom commands feature

### DISCUSSION THREAD

**Discussion by idursun** [idursun/jjui#63] [Ideas]
I have just merged some work around enabling use of custom commands from the `jjui`.

There will be a new configuration section called `custom_commands`, e.g.:

```toml
[custom_commands]
"show diff" = { key = ["U"], args = ["diff", "-r", "$change_id", "--color", "always"], show = "diff" }
"show oplog diff" = { key = ["ctrl+o"], args = ["op", "show",  "$operation_id", "--color", "always"], show = "diff" }
"resolve vscode" = { key = ["R"], args = ["resolve", "--tool", "vscode"], show = "interactive" }
"new main" = { args = ["new", "main"] }
"tug" = { key = ["ctrl+t"], args = ["bookmark", "move", "--from", "closest_bookmark($change_id)", "--to", "closest_pushable($change_id)"] }
```

<img width="429" alt="image" src="https://github.com/user-attachments/assets/711c4884-1202-4b73-b7fb-8423750a0692" />

In this feature, custom commands menu can be opened by pressing `x` key. Additionally, each custom command can have a dedicated optional custom key binding which you can invoke it without having to open the custom commands menu.

Custom commands can have placeholder arguments like `$change_id`, `$operation_id` and `$file`. Custom command window is also context aware so it won't show the commands that have place holder but not applicable to the selected item.

There is also a `show` argument which you can set it to be: 
* `none` (default); command will run as is and will only be displayed in the status bar.
* `diff`: the output of the command will be displayed in the diff viewer.
* `interactive`: the command run in interactive mode similar to `diffedit`, `split`, `commit` etc.

I didn't have time to test it thoroughly but it is already merged to main because it is not changing any of the existing behaviour. I am very likely to do a couple more iterations before calling it done.

Feel free to comment on areas that I might have missed.

**Comment by Adda0** [comment]
Seems to be working great. Thank you :heart:

I think that the only thing missing for me is being able to query the user for custom input to these custom commands. E.g., I would like to create a custom command to create a new bookmark for the current revision. The command should support `bookmark set --revision $change_id $inputs.bookmark_name` where `$prompts` is an array of user inputs specified in the custom command, and the `.bookmark_name` is the specific user input with the value inserted by the user when invoking the custom command through an interactive text field. Something like:
```toml
[custom_commands]
"new bookmark" = { 
  key = ["ctrl+b"], 
  args = ["bookmark", "set", "--revision", "$change_id", "$prompts.bookmark_name"],
  prompts = [ {id = bookmark_name, type = "text", title = "Name of the new bookmark"} ]
}
```
The `prompts.type` could be selecting from a menu (with filtering support), inputting a custom text, ...

Similarly to what [Lazygit does with prompts](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md):
```yaml
  - key: 'n'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git flow {{.Form.BranchType}} start {{.Form.BranchName}}"
    loadingText: 'Creating branch'
```
