### ISSUE TITLE
Non-git backend support

### ISSUE THREAD

**Issue by danpalmer** [idursun/jjui#89]
First off, congrats on the release, and also if you want to stick to just features you'll use personally that's fine.

However, it would be great to get support for non-git backends. I use jj as my main version control system, but not on top of git. Most features work here, but I can't push or pull commits.

One way this could potentially work, given that you may not have a non-git backend to test with, and given that they could theoretically do anything they like, is to make the git screen and commands config options. Perhaps something like this...

```toml
[backend_options]
name = "foo"
shortcut = "f"
commands = [
  { command = "jj foo upload", description = "Upload changes" },
  { command = "jj foo sync", description = "Sync with foo backend" },
]
```
